using System.Collections.Generic;
using System.Collections.Immutable;
using Bloody.NET;
using RGB.NET.Core;

namespace RGB.NET.Devices.Bloody.Keyboard;

public static class KeyboardLedMap
{
    public static readonly ImmutableDictionary<LedId, Key> LedMap = new Dictionary<LedId, Key>
    {
        [LedId.Keyboard_Escape] = Key.ESC,
        [LedId.Keyboard_GraveAccentAndTilde] = Key.TILDE,
        [LedId.Keyboard_Tab] = Key.TAB,
        [LedId.Keyboard_LeftShift] = Key.LEFT_SHIFT,
        [LedId.Keyboard_CapsLock] = Key.CAPS_LOCK,
        [LedId.Keyboard_LeftCtrl] = Key.LEFT_CONTROL,
        [LedId.Keyboard_LeftGui] = Key.LEFT_WINDOWS,
        [LedId.Keyboard_1] = Key.ONE,
        [LedId.Keyboard_2] = Key.TWO,
        [LedId.Keyboard_3] = Key.THREE,
        [LedId.Keyboard_4] = Key.FOUR,
        [LedId.Keyboard_5] = Key.FIVE,
        [LedId.Keyboard_6] = Key.SIX,
        [LedId.Keyboard_7] = Key.SEVEN,
        [LedId.Keyboard_8] = Key.EIGHT,
        [LedId.Keyboard_9] = Key.NINE,
        [LedId.Keyboard_0] = Key.ZERO,
        [LedId.Keyboard_F1] = Key.F1,
        [LedId.Keyboard_F2] = Key.F2,
        [LedId.Keyboard_F3] = Key.F3,
        [LedId.Keyboard_F4] = Key.F4,
        [LedId.Keyboard_F5] = Key.F5,
        [LedId.Keyboard_F6] = Key.F6,
        [LedId.Keyboard_F7] = Key.F7,
        [LedId.Keyboard_F8] = Key.F8,
        [LedId.Keyboard_F9] = Key.F9,
        [LedId.Keyboard_F10] = Key.F10,
        [LedId.Keyboard_F11] = Key.F11,
        [LedId.Keyboard_F12] = Key.F12,
        [LedId.Keyboard_Q] = Key.Q,
        [LedId.Keyboard_A] = Key.A,
        [LedId.Keyboard_W] = Key.W,
        [LedId.Keyboard_S] = Key.S,
        [LedId.Keyboard_Z] = Key.Z,
        [LedId.Keyboard_LeftAlt] = Key.LEFT_ALT,
        [LedId.Keyboard_E] = Key.E,
        [LedId.Keyboard_D] = Key.D,
        [LedId.Keyboard_X] = Key.X,
        [LedId.Keyboard_R] = Key.R,
        [LedId.Keyboard_C] = Key.C,
        [LedId.Keyboard_T] = Key.T,
        [LedId.Keyboard_G] = Key.G,
        [LedId.Keyboard_V] = Key.V,
        [LedId.Keyboard_Y] = Key.Y,
        [LedId.Keyboard_H] = Key.H,
        [LedId.Keyboard_B] = Key.B,
        [LedId.Keyboard_Space] = Key.SPACE,
        [LedId.Keyboard_U] = Key.U,
        [LedId.Keyboard_J] = Key.J,
        [LedId.Keyboard_N] = Key.N,
        [LedId.Keyboard_I] = Key.I,
        [LedId.Keyboard_K] = Key.K,
        [LedId.Keyboard_M] = Key.M,
        [LedId.Keyboard_O] = Key.O,
        [LedId.Keyboard_L] = Key.L,
        [LedId.Keyboard_F] = Key.F,
        [LedId.Keyboard_P] = Key.P,
        [LedId.Keyboard_CommaAndLessThan] = Key.COMMA,
        [LedId.Keyboard_SemicolonAndColon] = Key.SEMICOLON,
        [LedId.Keyboard_PeriodAndBiggerThan] = Key.PERIOD,
        [LedId.Keyboard_RightAlt] = Key.RIGHT_ALT,
        [LedId.Keyboard_MinusAndUnderscore] = Key.MINUS,
        [LedId.Keyboard_BracketLeft] = Key.OPEN_BRACKET,
        [LedId.Keyboard_ApostropheAndDoubleQuote] = Key.APOSTROPHE,
        [LedId.Keyboard_SlashAndQuestionMark] = Key.FORWARD_SLASH,
        [LedId.Keyboard_Function] = Key.FN_Key,
        [LedId.Keyboard_EqualsAndPlus] = Key.EQUALS,
        [LedId.Keyboard_BracketRight] = Key.CLOSE_BRACKET,
        [LedId.Keyboard_Backslash] = Key.BACKSLASH,
        [LedId.Keyboard_RightShift] = Key.RIGHT_SHIFT,
        [LedId.Keyboard_Application] = Key.APPLICATION_SELECT,
        [LedId.Keyboard_Backspace] = Key.BACKSPACE,
        [LedId.Keyboard_Enter] = Key.ENTER,
        [LedId.Keyboard_RightCtrl] = Key.RIGHT_CONTROL,
        [LedId.Keyboard_PrintScreen] = Key.PRINT_SCREEN,
        [LedId.Keyboard_Insert] = Key.INSERT,
        [LedId.Keyboard_Delete] = Key.DELETE,
        [LedId.Keyboard_ArrowLeft] = Key.ARROW_LEFT,
        [LedId.Keyboard_ScrollLock] = Key.SCROLL_LOCK,
        [LedId.Keyboard_Home] = Key.HOME,
        [LedId.Keyboard_End] = Key.END,
        [LedId.Keyboard_ArrowUp] = Key.ARROW_UP,
        [LedId.Keyboard_ArrowDown] = Key.ARROW_DOWN,
        [LedId.Keyboard_PauseBreak] = Key.PAUSE_BREAK,
        [LedId.Keyboard_PageUp] = Key.PAGE_UP,
        [LedId.Keyboard_PageDown] = Key.PAGE_DOWN,
        [LedId.Keyboard_ArrowRight] = Key.ARROW_RIGHT,
        [LedId.Keyboard_Custom1] = Key.LEFT_BAR,
        [LedId.Keyboard_Custom2] = Key.RIGHT_BAR,
        [LedId.Keyboard_NumLock] = Key.NUM_LOCK,
        [LedId.Keyboard_NumSlash] = Key.NUM_SLASH,
        [LedId.Keyboard_NumAsterisk] = Key.NUM_ASTERISK,
        [LedId.Keyboard_NumMinus] = Key.NUM_MINUS,
        [LedId.Keyboard_Num7] = Key.NUM_SEVEN,
        [LedId.Keyboard_Num8] = Key.NUM_EIGHT,
        [LedId.Keyboard_Num9] = Key.NUM_NINE,
        [LedId.Keyboard_NumPlus] = Key.NUM_PLUS,
        [LedId.Keyboard_Num4] = Key.NUM_FOUR,
        [LedId.Keyboard_Num5] = Key.NUM_FIVE,
        [LedId.Keyboard_Num6] = Key.NUM_SIX,
        [LedId.Keyboard_Num1] = Key.NUM_ONE,
        [LedId.Keyboard_Num2] = Key.NUM_TWO,
        [LedId.Keyboard_Num3] = Key.NUM_THREE,
        [LedId.Keyboard_NumEnter] = Key.NUM_ENTER,
        [LedId.Keyboard_Num0] = Key.NUM_ZERO,
        [LedId.Keyboard_NumPeriodAndDelete] = Key.NUM_PERIOD,
    }.ToImmutableDictionary();
}